name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme
    runs-on: macos-14
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
          xcodebuild clean build analyze test -scheme WeatherApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
